version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
